steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--tag=gcr.io/homebantoo/my-image']
options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: github@homebantoo.iam.gserviceaccount.com